server:
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
  port: 8081
  servlet:
    context-path: /testUrl

spring:
 profiles:
   active: dev

    
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:mybatis.xml
  
SMS:
  sid: 3e565f358ae0619f5a12817485b90ad5
  token: 10d0c36066d81dc462a335413c56b667
  appid: d37c497c4ca5481ca65bef9954e0a024



  
