spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
#    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chinaunicom_vms_zj?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      minimum-idle: 5
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
redis:
    database: 0
    host: localhost
    port: 6379
    password: ''
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0
    timeout: 1000
    session:
     store-type: none